### ISSUE TITLE
Метод SumGenre класса Player.java возвращает 0 вместо количества часов.

### ISSUE THREAD

**Issue by NovSeUr** [TarankovaAnna/Team-Project#1]
# Описание
Тест метода sumGenre (метод для подсчета суммарного времени в одном жанре заданным игроком) падает.
# Локализация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/a384b954fbf344045d99948803d845b455d45028/src/main/java/ru/netology/Player.java#L53-L63
# Шаги воспроизведения
1. Открыть [код](https://github.com/TarankovaAnna/Team-Project) в программе IDEA.
2. Запустить тест [SumGenreIfOneGame](https://github.com/TarankovaAnna/Team-Project/blob/a384b954fbf344045d99948803d845b455d45028/src/main/java/ru/netology/Player.java#L53-L63).
3. Посмотреть на вывод результата в консоли.
**Ожидаемый результат:** Тест пройден успешно.
**Фактический результат:** Тест упал с ошибкой AssertionFailedError: 

# Скриншот

![Баг репорт SumGenre](https://user-images.githubusercontent.com/116716541/227204100-49f85683-14fc-4936-9b22-fd77006a32f7.png)

# Окружение

- Windows 10 Pro
- IDEA: IntelliJ IDEA 2022.3.3 (Community Edition)
- Java: OpenJDK 11

**Comment by TarankovaAnna** [comment]
Тест проходит.
https://github.com/TarankovaAnna/Team-Project/blob/625e63ae03a81d86818b94b731e41d4945f5423a/src/test/java/ru/netology/PlayerTest.java#L31-L41


https://user-images.githubusercontent.com/121609317/227772491-7abee938-6087-45c3-a07c-10a3e2738f9a.mp4

**Comment by TarankovaAnna** [comment]
Внесены правки в метод sumGenre.
https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/main/java/ru/netology/Player.java#L88-L96



Тест [shouldSumGenreIfOneGame](https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/test/java/ru/netology/PlayerTest.java#L31-L41) проходит.

![shouldSum](https://user-images.githubusercontent.com/121609317/227957375-ebeeaa62-1e41-49aa-ac18-4fd54a9e2435.png)
