### ISSUE TITLE
Метод MostPlayedByGenre класса Player не возвращает игру

### ISSUE THREAD

**Issue by NovSeUr** [TarankovaAnna/Team-Project#10]
# Описание
Метод MostPlayedByGenre не возвращает игру в которой игрок провел большее количество часов, всегда возвращает null.
Так как логика метода на данный момент отсутствует.
# Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/625e63ae03a81d86818b94b731e41d4945f5423a/src/main/java/ru/netology/Player.java#L69-L71

# Шаги для воспроизведения
1. Открыть [код](https://github.com/TarankovaAnna/Team-Project) в программе IDEA.
2. Запустить тест [testShouldSearchMostPlayedByGenreGameIfInstalled](https://github.com/TarankovaAnna/Team-Project/blob/625e63ae03a81d86818b94b731e41d4945f5423a/src/test/java/ru/netology/PlayerTest.java#L98-L114).
3. Посмотреть на вывод результата в консоли.
**Ожидаемый результат:** Тест пройден успешно.
**Фактический результат:** Тест упал с ошибкой AssertionFailedError: 

# Скриншот
![MostByGenre](https://user-images.githubusercontent.com/116716541/227557829-37fa03fa-7f3b-47f9-9749-34362c773de1.png)

# Окружение
- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
- **Java:** OpenJDK 11

**Comment by TarankovaAnna** [comment]
Добавлена логика метода mostPlayedByGenre
https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/main/java/ru/netology/Player.java#L106-L120

Тест [testShouldSearchMostPlayedByGenreGameIfInstalled](https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/test/java/ru/netology/PlayerTest.java#L99-L115) проходит.
