### ISSUE TITLE
Метод play класса Player.java не ведет подсчет часов

### ISSUE THREAD

**Issue by NovSeUr** [TarankovaAnna/Team-Project#2]
# Описание
Тест метода **play** (метод для подсчета суммарного времени проведенного в игре с передачей в каталог) при воспроизведении падает.

# Локализация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/a384b954fbf344045d99948803d845b455d45028/src/main/java/ru/netology/Player.java#L39-L47

# Шаги для воспроизведения
1. Открыть [код](https://github.com/TarankovaAnna/Team-Project) программы в IDEA.
2. Запустить тест [testShouldCountedHoursWhenTheGameInstalled](https://github.com/TarankovaAnna/Team-Project/blob/625e63ae03a81d86818b94b731e41d4945f5423a/src/test/java/ru/netology/PlayerTest.java#L87-L95).
3. Посмотреть вывод в консоли.
**Ожидаемый результат:** Тест проходит успешно.
**Фактический результат:** Тест падает с ошибкой - AssertionFailedError: 

# Скриншот
![Баг репорт Play1](https://user-images.githubusercontent.com/116716541/227219496-6bde660e-e2fe-44c9-8cfc-47f98debe70e.png)

# Окружение
Операционная система: Windows 10 Pro
IDE: IntelliJ IDEA 2022.3 (Community Edition)
Java: OpenJDK 11

**Comment by TarankovaAnna** [comment]
Добавлен HashMap addGame, отредактирован метод installGame https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/main/java/ru/netology/Player.java#L31-L36

Отредактирован метод play https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/main/java/ru/netology/Player.java#L55-L69

Тест [testShouldCountedHoursWhenTheGameInstalled](https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/test/java/ru/netology/PlayerTest.java#L88-L96) проходит.
![counted](https://user-images.githubusercontent.com/121609317/227974593-6e842ffe-6250-4a8c-abd9-392b6d471c4e.png)
