### ISSUE TITLE
Метод containsGame класса GameStore возвращает false, если в каталог добавлена только одна игра

### ISSUE THREAD

**Issue by TarankovaAnna** [TarankovaAnna/Team-Project#3]
### Описание
Когда в каталог добавлена только одна игра, метод containsGame, (который проверяет наличие игры в каталоге и возвращает true, если игра есть и false, если игры нет) возвращает false.

### Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/86c540194896d89de51dc4d53b6ed9ac301b349a/src/main/java/ru/netology/GameStore.java#L32-L39

### Шаги воспроизведения

1. Открыть [код](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java)
2. Закомментить Тест 4, Тест 5 и Тест 6
3. Запустить тест [shouldAddGame](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L14-L20)
4. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит
**Фактический результат:** тест падает с ошибкой AssertionFailedError

# Скриншот
![Баг 1](https://user-images.githubusercontent.com/121609317/227369677-fd091850-1fe7-4a0f-9981-a2c922dca534.png)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by NovSeUr** [comment]
Исправлен метод containsGame.
https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L32-L39
Тест [shouldAddGame](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L14-L20) проходит.
