### ISSUE TITLE
Метод containsGame класса GameStore не находит последнюю добавленную игру, если в каталог добавлено более двух игр

### ISSUE THREAD

**Issue by TarankovaAnna** [TarankovaAnna/Team-Project#4]
### Описание
Когда в каталог добавлено более двух игр, метод containsGame, (который проверяет наличие игры в каталоге и возвращает true, если игра есть и false, если игры нет), при проверке наличия последней добавленной игры, возвращает false.

### Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/86c540194896d89de51dc4d53b6ed9ac301b349a/src/main/java/ru/netology/GameStore.java#L32-L39

### Шаги воспроизведения

1. Открыть [код](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java)
2. Закомментить Тест 4, Тест 5 и Тест 6
3. Запустить тест [shouldAddSomeGames](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L23-L30)
4. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит
**Фактический результат:** тест падает с ошибкой AssertionFailedError

# Скриншот
![Баг2](https://user-images.githubusercontent.com/121609317/227376273-aa794a9f-c14d-42a2-9ebb-e0f8ce3702b0.png)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by NovSeUr** [comment]
Исправлен метод containsGame.
https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L32-L39
Тест [shouldAddSomeGames](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L23-L30) проходит.
