### ISSUE TITLE
Метод addPlayTime класса GameStore не регистрирует количество проигранного времени

### ISSUE THREAD

**Issue by TarankovaAnna** [TarankovaAnna/Team-Project#5]
### Описание
Метод addPlayTime ничего не возвращает.

### Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/86c540194896d89de51dc4d53b6ed9ac301b349a/src/main/java/ru/netology/GameStore.java#L46-L52

### Шаги воспроизведения

1. Открыть [код](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java)
2. Закомментить Тест 5 и Тест 6
3. Запустить тест [shouldAddTimeIfAlreadyPlayed](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L43-L56)
4. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит
**Фактический результат:** тест падает с ошибкой "void cannot be converted to java.lang.Integer"

# Скриншот
![Баг 3](https://user-images.githubusercontent.com/121609317/227378799-701a1a28-504a-43b6-8f36-64c35dbea27e.png)
![Баг 3-1](https://user-images.githubusercontent.com/121609317/227378801-7168404f-f2b1-44c6-b9ef-7d888fefa866.png)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by NovSeUr** [comment]
Исправлен метод [addPlayTime](https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L46-L54).
https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L46-L54
Тест [shouldAddTimeIfAlreadyPlayed](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L43-L56) проходит.
