### ISSUE TITLE
Метод getMostPlayer класса GameStore не находит игрока, если он единственный играл 1 час

### ISSUE THREAD

**Issue by TarankovaAnna** [TarankovaAnna/Team-Project#6]
### Описание
Если в игры каталога GameStore играл 1 час только один игрок, а у остальных игроков время игры - 0 часов, метод getMostPlayer класса GameStore не находит этого игрока.

### Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/86c540194896d89de51dc4d53b6ed9ac301b349a/src/main/java/ru/netology/GameStore.java#L58-L69

### Шаги воспроизведения

1. Открыть [код](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java)
2. Закомментить Тест 4, Тест 5 и Тест 6
3. Запустить тест [shouldPlayMostIfPlayOneHour](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L143-L158)
4. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит
**Фактический результат:** тест падает с ошибкой AssertionFailedError

# Скриншот
![Баг 4](https://user-images.githubusercontent.com/121609317/227381876-75982ddf-e9de-4560-9a11-997c43dcb4cf.png)
![Баг 4-1](https://user-images.githubusercontent.com/121609317/227381879-36d20e32-9228-4abf-aff5-49f7c3781ec3.png)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by NovSeUr** [comment]
Исправлен метод [getMostPlayer]().
https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L60-L71
Тест: [shouldPlayMostIfOneHoure](https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/test/java/ru/netology/GameStoreTest.java#L138-L152) - проходит.
