### ISSUE TITLE
Метод getSumPlayedTime класса GameStore не суммирует время 

### ISSUE THREAD

**Issue by TarankovaAnna** [TarankovaAnna/Team-Project#8]
### Описание
Метод getSumPlayedTime не суммирует общее количество времени всех игроков, проведенного за играми из каталога GameStore. Метод всегда возвращает 0.

### Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/86c540194896d89de51dc4d53b6ed9ac301b349a/src/main/java/ru/netology/GameStore.java#L75-L77

### Шаги воспроизведения

1. Открыть [код](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java)
2. Закомментить Тест 4, Тест 5 и Тест 6
3. Запустить тест [shouldSumTimeIfSomePlayers](https://github.com/TarankovaAnna/Team-Project/blob/2ba116fcd968f62ea1daf60130114f4d09610f8d/src/test/java/ru/netology/GameStoreTest.java#L162-L181)
4. Посмотреть на вывод в консоли

**Ожидаемый результат:** тест проходит
**Фактический результат:** тест падает с ошибкой AssertionFailedError

# Скриншот
![Баг 6](https://user-images.githubusercontent.com/121609317/227390499-874cad67-98b5-44d9-b30b-309e74ff9a3f.png)
![Баг 6-1](https://user-images.githubusercontent.com/121609317/227390503-96cb21e6-d11f-4cad-89e8-f200e5c11405.png)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA 2022.3.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by NovSeUr** [comment]
Добавлена логика метода [getSumPlayedTime](https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L78-L84).
https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/main/java/ru/netology/GameStore.java#L78-L84
Тесты:

- [shouldSumTimeIfSomePlayers](https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/test/java/ru/netology/GameStoreTest.java#L156-L174)

- [shouldSumTimeIfOnePlayer](https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/test/java/ru/netology/GameStoreTest.java#L177-L189)

- [shouldSumTimeIfNoOnePlayersGame](https://github.com/TarankovaAnna/Team-Project/blob/8677e6b7ff1a780dcf4db43398d043e522f992ab/src/test/java/ru/netology/GameStoreTest.java#L192-L200)

Проходят.
