### ISSUE TITLE
Метод play класса Player не выкидывает RuntimeException при неустановленной игре

### ISSUE THREAD

**Issue by NovSeUr** [TarankovaAnna/Team-Project#9]
# Описание
Метод play при воспроизведении, в случае неустановленной игры не выкидывает Runtimeexception, так как на данный момент Runtimeexception отсутствует.
# Локация дефекта
https://github.com/TarankovaAnna/Team-Project/blob/625e63ae03a81d86818b94b731e41d4945f5423a/src/main/java/ru/netology/Player.java#L39-L47

# Шаги для воспроизведения
1. Открыть [код](https://github.com/TarankovaAnna/Team-Project) в программе IDEA.
2. Запустить тест [testShouldThrowRunTimeExceptionWhenTheGameNotInstalled](https://github.com/TarankovaAnna/Team-Project/blob/625e63ae03a81d86818b94b731e41d4945f5423a/src/test/java/ru/netology/PlayerTest.java#L81-L84).
3. Посмотреть на вывод результата в консоли.
**Ожидаемый результат:** Тест пройден успешно.
**Фактический результат:** Тест упал с ошибкой AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![Баг репорт Play Runtimeexception](https://user-images.githubusercontent.com/116716541/227554534-19021c9a-2f6c-44a1-9088-a87975f5dfba.png)

# Окружение
- Операционная система: Windows 10
- IDE: IntelliJ IDEA 2022.3 (Community Edition)
- Java: OpenJDK 11

**Comment by TarankovaAnna** [comment]
Метод play исправлен, добавлено исключение
https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/main/java/ru/netology/Player.java#L55-L69

Тест [testShouldThrowRunTimeExceptionWhenTheGameNotInstalled](https://github.com/TarankovaAnna/Team-Project/blob/4cc92dfdbe90494c2c3aebc2c20cbee639da7b58/src/test/java/ru/netology/PlayerTest.java#L82-L85) проходит.
